### PR TITLE
drumn added

### PR DESCRIPTION
**Pull request by Gaurav05082002**
this is a musical drum made with javascript, the webpage produces drum beats on pressing keys. please accept this as my contribution under hacktober fest

### CODE REVIEW

**Comment by Gaurav05082002** [comment]
please accept this as my contribution under hacktober fest , if any issue is coming in merging it please inform

**Comment by TKirtan** [comment]
There's a conflict in your commit, check it out once with new commits and also check if you haven't removed someone else codes.

**Comment by Gaurav05082002** [comment]
> There's a conflict in your commit, check it out once with new commits and also check if you haven't removed someone else codes.

for this a new pull request named "MUSICAL DRUM ADDED" is opened , new one does not have any conflict and all codes are present there, please accept it

**Comment by TKirtan** [comment]
Okay

**Comment by Gaurav05082002** [comment]
> Okay

https://github.com/codemistic/Web-Development/pull/330 , this is link for the new one, please merge it

**Pull request closed without merging**
