### PR TITLE
Loading Animation

### PR DESCRIPTION
**Pull request by imDatt777**
A colorful loading animation built using HTML and CSS which can be used as a loader in various projects by modifying it according to your own needs.

### CODE REVIEW

**Comment by projectsop** [comment]
I already added it github.com/codemistic/preloader

**Comment by imDatt777** [comment]
If you can accept and add 3 todo list then why not this. It is different from the one you built

**Comment by projectsop** [comment]
Ok btw thank you for telling

**Comment by projectsop** [comment]
I would like to tell you that where we will write our code in this animation
Suggestion:
Where we will write our code add this line:

**Pull request merged**
