### PR TITLE
adding styleMe an Ecomerce website project

### PR DESCRIPTION
**Pull request by Mayank2808sharma**
I have added an e-commerce website project on which i have been working on lately

### CODE REVIEW

**Comment by TKirtan** [comment]
Will solve these conflict soon.

**Comment by Mayank2808sharma** [comment]
Hi, I am contributing for the first time ever so I am a little confused.
should I do the whole process again by keeping in mind not to get into conflict and send another merge request or the maintainer will solve this merge issue?

**Comment by TKirtan** [comment]
Try resolving it by yourself, You can code and send new pull request, try not to delete someone else code, if you want to edit and improve someone else code then mention the file names properly in description.

**Comment by projectsop** [comment]
As this commit has some conflict pls close this pr as others pr are not being accepted

**Comment by TKirtan** [comment]
Please check for the conflict happening for pr. Update the chances in the repo and work with your code.

**Comment by TKirtan** [comment]
DM me, So that I can help you with the conflict and doubts.

**Pull request closed without merging**
